version: '3.3'

services:
   frontend22:
     stdin_open: true
     container_name: app2
     image: 'anjnadockerid1/hackathonfrontend:v22'
     build:
       dockerfile: Dockerfile
       context: ./stocks-react-master
     ports:
       - "3000:3000"
     depends_on:
       - backend22
   backend22:
     container_name: backend22
     image: 'anjnadockerid1/hackathonbackend:v22'
     build:
       dockerfile: Dockerfile
       context: ./stocks-master
     ports:
       - "8700:8700"
     depends_on:
       - dbpostgresql
   worker22:
    container_name: worker22
    image: 'anjnadockerid1/hackathonworker:v22'
    build: 
      dockerfile: Dockerfile
      context: ./stocks-worker
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=password
      - PGPORT=5432
    ports:
      - "8084:8084"
    depends_on:
      - dbpostgresql
   dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres