apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
  annotations: service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    component: web
  ports:
    - port: 80
