apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  clusterIP: clusterIP: 10.0.113:249
  selector:
    component: server3
  ports:
    - port: 8700
      targetPort: 8700
