apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server3
  template:
    metadata:
      labels:
        component: server3
    spec:
      containers:
        - name: server3
          image: anjnaacr.azurecr.io/stocksserverbackend:v2
          ports:
            - containerPort: 8096
      restartPolicy: Always
      
