#version: '2'
#
#services:
#  app:
#    image: 'sample:hackathonbackend1'
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
#      - SPRING_DATASOURCE_USERNAME=compose-postgres
#      - SPRING_DATASOURCE_PASSWORD=compose-postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#
#  db:
#    image: 'postgres:13.1-alpine'
#    container_name: db
#    environment:
#      - POSTGRES_USER=compose-postgres
#      - POSTGRES_PASSWORD=compose-postgres

version: '3.2'
services:
  frontend:
    container_name: app
    image: 'sample:hackathonfrontend'
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    container_name: backend
    image: 'sample:hackathonbackend2'
    build: ./
    ports:
      - "8083:8083"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb