version: '3.3'

services:
   frontend33:
     stdin_open: true
     container_name: app33
     image: 'anjnadockerid1/hackathonfrontend:v33'
     build:
       dockerfile: Dockerfile
       context: ./stocks-react-master
     ports:
       - "3000:3000"
     depends_on:
       - backend33
   backend33:
     container_name: backend33
     image: 'anjnadockerid1/hackathonbackend:v33'
     build:
       dockerfile: Dockerfile
       context: ./stocks-master
     ports:
       - "8700:8700"
     depends_on:
       - worker33
   worker33:
    container_name: worker33
    image: 'anjnadockerid1/hackathonworker:v33'
    build: 
      dockerfile: Dockerfile
      context: ./stocks-worker
    ports:
      - "8084:8084"
    depends_on:
      - dbpostgresql
   dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb