version: '3.3'
services:
   frontend:
     stdin_open: true
     container_name: app
     image: 'anjnadockerid1/hackathonfrontend:v2'
     build:
       dockerfile: Dockerfile
       context: ./stocks-react-master
     ports:
       - "3002:3002"
     depends_on:
       - backend
   backend:
     container_name: backend
     image: 'anjnadockerid1/hackathonbackend:v2'
     build:
       dockerfile: Dockerfile
       context: ./stocks-master
     ports:
       - "8096:8096"
     depends_on:
       - worker
   worker:
    container_name: worker
    image: 'anjnadockerid1/hackathonworker:v2'
    build: 
      dockerfile: Dockerfile
      context: ./stocks-worker
    ports:
      - "8097:8097"
    depends_on:
      - dbpostgresql
   dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb