apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.207.98
  selector:
    component: server3
  ports:
    - port: 8700
      targetPort: 8700
