apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client33
          image: anjnaacr.azurecr.io/stocksserverfrontend:v3
          ports:
            - containerPort: 80
      restartPolicy: Always
